#!/bin/sh
rm -rf kernel/usr/initramfs/*
cp -R ../initramfs_sgh-i997r/* kernel/usr/initramfs
rm $(find kernel/usr/initramfs -name EMPTY_DIRECTORY -print)
rm -rf $(find kernel/usr/initramfs -name .git -print)
make dempseyR_rev00_defconfig
make -j16 && cp -a $(find . -name *.ko -print |grep -v initramfs) kernel/usr/initramfs/lib/modules/ && make -j16
mkdir ../built_zImages
cp arch/arm/boot/zImage ../built_zImages/zImage-rainbow
make dempseyR_norainbow_defconfig
make -j16 && cp -a $(find . -name *.ko -print |grep -v initramfs) kernel/usr/initramfs/lib/modules/ && make -j16
cp arch/arm/boot/zImage ../built_zImages/zImage-norainbow
# adb shell reboot download
# sleep 5
# heimdall flash --kernel arch/arm/boot/zImage
